---
# tasks file for openvpn

- name: Install packages
  yum: name=openvpn state=present

- name: Copy server configuration
  template: src=server.conf.j2 dest=/etc/openvpn/server.conf
            owner=root mode=0640
  notify: restart openvpn

- name: Copy server's certificates
  template: src={{ item }}.j2 dest=/etc/openvpn/{{ item }} owner=root mode=0600
  with_items:
    - ca.crt
    - server.key
    - server.crt
    - dh2048.pem
  notify: restart openvpn

- name: Configure firewall ports
  firewalld: service=openvpn permanent=yes immediate=yes state=enabled

- name: Check firewall routing status
  command: firewall-cmd --list-all
  register: masquerade_status
  changed_when: "'masquerade: no' in masquerade_status.stdout"

- name: Activate firewall routing
  command: firewall-cmd --add-masquerade
  when: "'masquerade: no' in masquerade_status.stdout"

- name: Enable firewall routing
  command: firewall-cmd --permanent --add-masquerade
  when: "'masquerade: no' in masquerade_status.stdout"

- name: Enable ip_forward
  lineinfile: dest=/etc/sysctl.conf regexp="^net.ipv4.ip_forward"
              state=present line="net.ipv4.ip_forward = 1" create=yes
  notify: restart network

- name: Enable and start openvpn
  service: name=openvpn@{{ openvpn_server_name }} state=started enabled=yes
