---

- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

    - name: Delete first instance
      ec2:
        region: us-east-2
        state: absent
        instance_ids: i-05663efbd18db1454
      ignore_errors: true
    
    - name: Provision a set of instances
      ec2:
        key_name: mykey
        instance_type: t2.micro
        image: ami-cfdafaaa
        wait: yes
        count: 1
        group: default
        region: us-east-2
        instance_tags:
          Name: NGINX
        vpc_subnet_id: subnet-b84d7cd1
        assign_public_ip: yes
      register: ec2

    - name: test some actions
      debug:
        msg: "{{ ec2 }}"





