nginx:
  image: tutum/nginx
  ports:
    - "8080:80"
  links:
    - phpfpm
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./index.html:/app/index.html

phpfpm:
  image: php:fpm
  ports:
    - "9000:9000"

mysql:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: admin

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - mysql
  ports:
    - "8183:80"
  restart: always
  environment:
    MYSQL_USERNAME: admin
    MYSQL_ROOT_PASSWORD: admin
    PMA_ARBITRARY: 1 
