---

- name: Create additional loopbackl for DNS listening
  include: create_int.yml
  tags:
    - create_int
  
- name: Set facts for other roles (dnsclient)
  set_fact: 
    # Use it update.ns jinja2 template
    zone_name: "{{ forward_zone_name }}"

- name: Installing BIND
  yum:
    name: bind
    state: latest

- name: Installs bind-utils
  yum: 
    name: bind-utils
    state: latest

- name: Upload config files to server
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'named.j2', dest: '/etc/named.conf' }
    - { src: 'forward_zone.j2', dest: '/var/named/data/{{ forward_zone_file }}' }
    - { src: 'reverse_zone.j2', dest: '/var/named/data/{{ reverse_zone_file }}' }
    - { src: 'ddserver.conf.j2', dest: '/etc/named/ddserver.conf' }

- name: Firewalld edit - add DNS to allow in public zone
  firewalld:
    zone: public
    service: dns
    permanent: true
    state: enabled
    immediate: yes

- name: Firewalld edit - add DNS to allow in internal zone
  firewalld:
    zone: internal
    service: dns
    permanent: true
    state: enabled
    immediate: yes


- lineinfile:
    path: /etc/resolv.conf
    line: "nameserver {{ ansible_default_ipv4.address }}"
    state: present


- name: restart bind
  shell: systemctl restart named   
  register: bind_start

