---

- hosts: all
  become: true 
  
  tasks:

  - name: Set authorized key took from file
    authorized_key:
      user: root
      state: present
      key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"

  - name: Set fact of vagrant's VM for use for edit hypervisor files  
    set_fact:
      ip: "{{ ansible_default_ipv4.address }}"
      hostname: "{{ ansible_hostname }}"
  
  - name: Renew hypervisor hosts file.
    local_action: shell sed -i '/{{ hostname }}/d' /etc/hosts
  
  - name: Renew hypervisor hosts file.
    local_action: shell echo >> /etc/hosts '{{ ip }} {{ hostname }}'
    
    
