---
galaxy_info:
  author: Juan Diego Romero Gonzalez
  description: OpenVPN installation for CentOS 7
  license: BSD
  min_ansible_version: 1.9
  platforms:
    - name: EL
      versions:
        - 7
  categories:
    - networking
  dependencies: []
