---
- hosts: dnsmaster
  become: true
  roles:
    - {role: named }
    - {role: kyl191.openvpn, clients: [client1, client2] }

- hosts: dnsclient
  gather_facts: no 
  become: true
  roles: 
    - {role: dns-client }
